### ISSUE TITLE
Is this a typo or intentional?

### ISSUE THREAD

**Issue by bonish** [armtronix/Wifi-Two-Dimmer-Board#1]
https://github.com/armtronix/Wifi-Two-Dimmer-Board/blob/c03112be31c32a8a7daabbe51ae783ece1ce2137/Arduino_Code/Wifi_Dimmer_two_TriacV0.2/serverFunctions.ino#L145

Shouldn't this be: `webtypeGlob = 1;`

**Comment by armtronix** [comment]
no
