### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by causalloop** [armtronix/Wifi-Two-Dimmer-Board#2]
Config file syntax?  Programming the ESP board - where's reset and/or flash buttons?  Do the two buttons on the board (not noted in the pictures) correspond to something?

I can't for the life of me get this to program.  I've used this FTDI board (looks just like the one in your pics actually) to program dozens of ESP devices, but something is wonky here.  Walk us through the config file and ESP programming like we've never done it before because this is not at all intuitive...  

Also, RTS/DTR/CTS - almost never have to use these pins and they're labeled differently on the FTDI boards.

A lot of this documentation seems cobbled together - and most of your other repos don't even have that much...  I don't understand how things can be sold undocumented with an expectation of functionality when there isn't even any troubleshooting help.

**Comment by armtronix** [comment]
Dear sir 
As we are using RTS and DTR you don't need a reset button for flashing , just select nodemcu 1.0 as the board while programming . 
Many ftdi standard boards (RTS, DTR)don't come with these pins exposed. you will have to find one  as this is required to switch between programming mode and application mode (some modules like this will have almost all pins exposed
https://www.ebay.com/itm/FT232RL-3-3V-5-5V-FTDI-USB-to-TTL-Serial-Adapter-Module-for-Arduino-Mini-Port/381374421597?epid=502148532&hash=item58cbafda5d:g:jk8AAOSwrklVMjIp)
You can also find some info here
http://www.instructables.com/id/Wifi-Two-Triac-Dimmer-Board/
Or contact us on our sales mail id

**Comment by causalloop** [comment]
As much as I hate admitting when I'm wrong... that fixed it.  That said (and I'm almost positive I'm using the exact same FTDI adapter), the stupid RTS pin is not in the row of pins at the back, it sits by itself on one side (which I guess could just be my OCD being bothered).. I don't think they make a 'single' connector for that one unless you're using a breadboard...

![rts pin](https://i.imgur.com/Y5NpI0f.jpg)

(And yes, that's heat shrink around the board, I was worried about it getting shorted with some of the other junk on my desk at the time)
