### ISSUE TITLE
Question sales

### ISSUE THREAD

**Issue by gibo77** [armtronix/Wifi-Two-Dimmer-Board#3]
Hi,
This is not an issue, but a question.
How much you think this would cost if you want to sell it.
Thanks!

**Comment by armtronix** [comment]
https://www.tindie.com/products/Armtronix/wifi-two-triac-board-one-dimmer-one-onoff/
https://www.tindie.com/products/Armtronix/wifi-dimmer-with-esp8266-and-atmega328p/

**Comment by armtronix** [comment]
Sir you will be able to purchase it through tindie
