### ISSUE TITLE
Error compiling for atmega328p

### ISSUE THREAD

**Issue by freddykat** [armtronix/Wifi-Two-Dimmer-Board#4]
Hello,
I've been trying to flash the arduino nano as per your instruction and have stoped on this problem. 
The error that ive got is this: 
`

In file included from C:\Users\BMW\Desktop\Wifi-Two-Dimmer-Board-master\Wifi-Two-Dimmer-Board-master\Arduino_Code\Atmega328_two_dimmerV0.5_Dimlib\Atmega328_two_dimmerV0.5_Dimlib.ino:10:0:

C:\Users\BMW\Documents\Arduino\libraries\SerialCommands-1.1.0\src/SerialCommands.h:42:80: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

  SerialCommands(Stream* serial, char* buffer, int16_t buffer_len, char* term = "\r\n", char* delim = " ") :

                                                                                ^~~~~~

C:\Users\BMW\Documents\Arduino\libraries\SerialCommands-1.1.0\src/SerialCommands.h:42:102: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

  SerialCommands(Stream* serial, char* buffer, int16_t buffer_len, char* term = "\r\n", char* delim = " ") :

                                                                                                      ^~~

C:\Users\BMW\Desktop\Wifi-Two-Dimmer-Board-master\Wifi-Two-Dimmer-Board-master\Arduino_Code\Atmega328_two_dimmerV0.5_Dimlib\Atmega328_two_dimmerV0.5_Dimlib.ino:26:68: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

 SerialCommands serComm(&Serial, serBuff, sizeof(serBuff),"\n", ":,");

                                                                    ^

C:\Users\BMW\Desktop\Wifi-Two-Dimmer-Board-master\Wifi-Two-Dimmer-Board-master\Arduino_Code\Atmega328_two_dimmerV0.5_Dimlib\Atmega328_two_dimmerV0.5_Dimlib.ino:26:68: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

C:\Users\BMW\Desktop\Wifi-Two-Dimmer-Board-master\Wifi-Two-Dimmer-Board-master\Arduino_Code\Atmega328_two_dimmerV0.5_Dimlib\Atmega328_two_dimmerV0.5_Dimlib.ino:36:24: warning: array must be initialized with a brace-enclosed initializer [-fpermissive]

 movingAvg knobAvg[2](10);

                        ^

C:\Users\BMW\Desktop\Wifi-Two-Dimmer-Board-master\Wifi-Two-Dimmer-Board-master\Arduino_Code\Atmega328_two_dimmerV0.5_Dimlib\Atmega328_two_dimmerV0.5_Dimlib.ino: In function 'void cmdStatus(SerialCommands*)':

Atmega328_two_dimmerV0.5_Dimlib:59:43: error: 'class Dimmer' has no member named 'getSetValue'; did you mean 'getValue'?

     sender->GetSerial()->print(dimmers[i].getSetValue());

                                           ^~~~~~~~~~~

                                           getValue

Atmega328_two_dimmerV0.5_Dimlib:64:43: error: 'class Dimmer' has no member named 'getSetValue'; did you mean 'getValue'?

     sender->GetSerial()->print(dimmers[i].getSetValue());

                                           ^~~~~~~~~~~

                                           getValue

C:\Users\BMW\Desktop\Wifi-Two-Dimmer-Board-master\Wifi-Two-Dimmer-Board-master\Arduino_Code\Atmega328_two_dimmerV0.5_Dimlib\Atmega328_two_dimmerV0.5_Dimlib.ino: In function 'void setup()':

C:\Users\BMW\Desktop\Wifi-Two-Dimmer-Board-master\Wifi-Two-Dimmer-Board-master\Arduino_Code\Atmega328_two_dimmerV0.5_Dimlib\Atmega328_two_dimmerV0.5_Dimlib.ino:122:29: warning: invalid conversion from 'void (*)(SerialCommands*)' to 'void (*)(SerialCommands*, const char*)' [-fpermissive]

   serComm.SetDefaultHandler(&cmdUnrecognized);

                             ^~~~~~~~~~~~~~~~

In file included from C:\Users\BMW\Desktop\Wifi-Two-Dimmer-Board-master\Wifi-Two-Dimmer-Board-master\Arduino_Code\Atmega328_two_dimmerV0.5_Dimlib\Atmega328_two_dimmerV0.5_Dimlib.ino:10:0:

C:\Users\BMW\Documents\Arduino\libraries\SerialCommands-1.1.0\src/SerialCommands.h:92:7: note:   initializing argument 1 of 'void SerialCommands::SetDefaultHandler(void (*)(SerialCommands*, const char*))'

  void SetDefaultHandler(void(*function)(SerialCommands*, const char*));

       ^~~~~~~~~~~~~~~~~

exit status 1
'class Dimmer' has no member named 'getSetValue'; did you mean 'getValue'?`

The program stops at the following line:

`  }
    sender->GetSerial()->print(dimmers[i].getSetValue());`

Does anyone have a clue how to fix it?
Thanks

**Comment by armtronix** [comment]
I think you have modified the code, cant help much unless you share your code .

**Comment by freddykat** [comment]
Partially solved as now the file is correct.
Was due having 2 versions in the same paste.
BUT now I face the problem of re-flash the 328p because as soon as I plug the programmer on it, it loads the dimmer. I was incapable of flashing it or even put the bootloader again.
The dimmer works, but is incompatible with tasmota and is a problem to me how to put the 328p on flash mode.
I have it on 0.3 both dimmable and want to put the v0.4 tasmota version on it.
Therefore I'm still stoped here.... theres a way of stop the serial com to occur on the 328p so it dont block the programmer trafic?

**Comment by armtronix** [comment]
plz refer to this http://armtronix.net/2019/04/18/loading-tasmota-firmware-on-armtronix-single-triac-board/
Do not try to load board loader it will spot the board and will be very difficult to reflash the bootloader  as they are only spi pads no pins for SPI based ISP programming  . You will need tx,rx,dtr ground pin based ftdi usb to uart converter
